// -------------------------------------------------------------------------
// myFP2ESP32 STATIONMODE CONFIGURATION
// © Copyright Robert Brown 2020-2022.
// All Rights Reserved.
// -------------------------------------------------------------------------


// -------------------------------------------------------------------------
// YOUR LOCAL NETWORK SSID AND PASSWORD
// -------------------------------------------------------------------------
// This is the Name and Password credentials used to log on to your local
// network. You will need to change these.
char mySSID[64] = "myfp2esp";
char myPASSWORD[64] = "myfp2esp";

// ALTERNATIVE NETWORK CREDENTIALS
char mySSID_1[64]     = "FireFox";            
char myPASSWORD_1[64] = "AllYeWhoEnter";  


// -------------------------------------------------------------------------
// DYNAMIC OR STATIC TCP/IP ADDRESS CONFIGURATION
// -------------------------------------------------------------------------
// If the controller gets its address from your network, then use STATICIPOFF
// If the controller needs a static address, then use STATICIPON
// Select ONLY ONE, either DYNAMICIP (default) or STATICIP

int staticip = DYNAMICIP;                   // IP address is generated by network device and is dynamic and can change
//int staticip = STATICIP;                  // IP address specified by controller - must be defined correctly

// -------------------------------------------------------------------------
// STATIC TCP/IP ADDRESS CONFIGURATION
// -------------------------------------------------------------------------
// If you have defined staticip to be STATICIP then you need to define the
// TCP/IP configuration the controller will be using.

IPAddress ip(192, 168, 2, 21);        // TCP/IP address for controller
IPAddress dns(192, 168, 2, 1);        // Your local network dns - normally address of your router
IPAddress gateway(192, 168, 2, 1);    // Your local network gateway - normally address of your router
IPAddress subnet(255, 255, 255, 0);   // Your local network subnet for broadcast messages

// controller_mode
// DO NOT CHANGE
int myfp2esp32mode = STATIONMODE;
